Default:
  env: prod
  baseURL: http://localhost:30000
  port: 8089
  containerPort: 80
  name: vue3-app
Development:
  baseURL: http://localhost:30000
  port: 8088
  containerPort: 80
  name: vue3-app:dev
  cdn: 
    externals: 
      vue: Vue
      vuex: Vuex
      vue-router: VueRouter
      axios: axios
      moment: moment
      echarts: echarts
    js: 
      - https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/vue/3.2.0/vue.global.js
      - https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/vuex/4.0.0/vuex.global.min.js
      - https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/vue-router/4.0.0/vue-router.global.min.js
      - https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/axios/0.26.0/axios.min.js
      - https://lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M/moment.js/2.29.1/moment.min.js
      - https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/echarts/5.3.0/echarts.min.js
Production:
  baseURL: http://localhost:30001
  port: 8099
  containerPort: 80
  name: vue3-app:prod
