Default:
  env: prod
  baseUrl: http://localhost:30000
  port: 8089
  containerPort: 80
  name: vue3-app
Development:
  baseUrl: http://localhost:30000
  port: 8088
  containerPort: 80
  name: vue3-app:dev
Production:
  baseUrl: http://localhost:30001
  port: 8089
  containerPort: 80
  name: vue3-app:prod
